/**
 * Comprehensive world airports database for local autocomplete.
 * ~480 aeroportos covering all commercially served airports worldwide.
 * Searched locally for instant results, supplemented by Amadeus API.
 */
export interface AirportEntry {
  iata: string;
  name: string;
  city: string;
  country: string;
  subType: "AIRPORT" | "CITY";
}

export const AIRPORTS_DB: AirportEntry[] = [
  // ===== BRAZIL =====
  { iata: "GRU", name: "Guarulhos Intl", city: "São Paulo", country: "BR", subType: "AIRPORT" },
  { iata: "CGH", name: "Congonhas", city: "São Paulo", country: "BR", subType: "AIRPORT" },
  { iata: "VCP", name: "Viracopos", city: "Campinas", country: "BR", subType: "AIRPORT" },
  { iata: "GIG", name: "Galeão Intl", city: "Rio de Janeiro", country: "BR", subType: "AIRPORT" },
  { iata: "SDU", name: "Santos Dumont", city: "Rio de Janeiro", country: "BR", subType: "AIRPORT" },
  { iata: "BSB", name: "Pres. Juscelino Kubitschek", city: "Brasília", country: "BR", subType: "AIRPORT" },
  { iata: "CNF", name: "Confins Intl", city: "Belo Horizonte", country: "BR", subType: "AIRPORT" },
  { iata: "PLU", name: "Pampulha", city: "Belo Horizonte", country: "BR", subType: "AIRPORT" },
  { iata: "SSA", name: "Dep. Luís Eduardo Magalhães", city: "Salvador", country: "BR", subType: "AIRPORT" },
  { iata: "REC", name: "Guararapes Intl", city: "Recife", country: "BR", subType: "AIRPORT" },
  { iata: "FOR", name: "Pinto Martins Intl", city: "Fortaleza", country: "BR", subType: "AIRPORT" },
  { iata: "POA", name: "Salgado Filho Intl", city: "Porto Alegre", country: "BR", subType: "AIRPORT" },
  { iata: "CWB", name: "Afonso Pena Intl", city: "Curitiba", country: "BR", subType: "AIRPORT" },
  { iata: "BEL", name: "Val de Cans Intl", city: "Belém", country: "BR", subType: "AIRPORT" },
  { iata: "MAO", name: "Eduardo Gomes Intl", city: "Manaus", country: "BR", subType: "AIRPORT" },
  { iata: "FLN", name: "Hercílio Luz Intl", city: "Florianópolis", country: "BR", subType: "AIRPORT" },
  { iata: "NAT", name: "São Gonçalo do Amarante", city: "Natal", country: "BR", subType: "AIRPORT" },
  { iata: "MCZ", name: "Zumbi dos Palmares", city: "Maceió", country: "BR", subType: "AIRPORT" },
  { iata: "AJU", name: "Santa Maria", city: "Aracaju", country: "BR", subType: "AIRPORT" },
  { iata: "SLZ", name: "Marechal Cunha Machado", city: "São Luís", country: "BR", subType: "AIRPORT" },
  { iata: "THE", name: "Senador Petrônio Portella", city: "Teresina", country: "BR", subType: "AIRPORT" },
  { iata: "CGB", name: "Marechal Rondon", city: "Cuiabá", country: "BR", subType: "AIRPORT" },
  { iata: "CGR", name: "Campo Grande Intl", city: "Campo Grande", country: "BR", subType: "AIRPORT" },
  { iata: "GYN", name: "Santa Genoveva", city: "Goiânia", country: "BR", subType: "AIRPORT" },
  { iata: "PMW", name: "Palmas", city: "Palmas", country: "BR", subType: "AIRPORT" },
  { iata: "PVH", name: "Gov. Jorge Teixeira", city: "Porto Velho", country: "BR", subType: "AIRPORT" },
  { iata: "BPS", name: "Porto Seguro", city: "Porto Seguro", country: "BR", subType: "AIRPORT" },
  { iata: "IOS", name: "Jorge Amado", city: "Ilhéus", country: "BR", subType: "AIRPORT" },
  { iata: "NVT", name: "Min. Victor Konder", city: "Navegantes", country: "BR", subType: "AIRPORT" },
  { iata: "VIX", name: "Eurico de Aguiar Salles", city: "Vitória", country: "BR", subType: "AIRPORT" },
  { iata: "JPA", name: "Pres. Castro Pinto", city: "João Pessoa", country: "BR", subType: "AIRPORT" },
  { iata: "IGU", name: "Cataratas Intl", city: "Foz do Iguaçu", country: "BR", subType: "AIRPORT" },
  { iata: "LDB", name: "Gov. José Richa", city: "Londrina", country: "BR", subType: "AIRPORT" },
  { iata: "MGF", name: "Silvio Name Junior", city: "Maringá", country: "BR", subType: "AIRPORT" },
  { iata: "UDI", name: "Ten. Cel. Aviador César Bombonato", city: "Uberlândia", country: "BR", subType: "AIRPORT" },
  { iata: "RAO", name: "Leite Lopes", city: "Ribeirão Preto", country: "BR", subType: "AIRPORT" },
  { iata: "SJP", name: "Prof. Eribelto Manoel Reino", city: "São José do Rio Preto", country: "BR", subType: "AIRPORT" },
  { iata: "PPB", name: "Pres. Prudente", city: "Presidente Prudente", country: "BR", subType: "AIRPORT" },
  { iata: "JOI", name: "Lauro Carneiro de Loyola", city: "Joinville", country: "BR", subType: "AIRPORT" },
  { iata: "CXJ", name: "Hugo Cantergiani", city: "Caxias do Sul", country: "BR", subType: "AIRPORT" },
  { iata: "PFB", name: "Lauro Kurtz", city: "Passo Fundo", country: "BR", subType: "AIRPORT" },
  { iata: "STM", name: "Maestro Wilson Fonseca", city: "Santarém", country: "BR", subType: "AIRPORT" },
  { iata: "MCP", name: "Alberto Alcolumbre Intl", city: "Macapá", country: "BR", subType: "AIRPORT" },
  { iata: "RBR", name: "Plácido de Castro Intl", city: "Rio Branco", country: "BR", subType: "AIRPORT" },
  { iata: "BVB", name: "Atlas Brasil Cantanhede", city: "Boa Vista", country: "BR", subType: "AIRPORT" },
  { iata: "JTC", name: "Bauru–Arealva", city: "Bauru", country: "BR", subType: "AIRPORT" },
  { iata: "MOC", name: "Mário Ribeiro", city: "Montes Claros", country: "BR", subType: "AIRPORT" },
  { iata: "IMP", name: "Pref. Renato Moreira", city: "Imperatriz", country: "BR", subType: "AIRPORT" },
  { iata: "CPV", name: "Pres. João Suassuna", city: "Campina Grande", country: "BR", subType: "AIRPORT" },
  { iata: "JDO", name: "Orlando Bezerra de Menezes", city: "Juazeiro do Norte", country: "BR", subType: "AIRPORT" },
  { iata: "PNZ", name: "Sen. Nilo Coelho", city: "Petrolina", country: "BR", subType: "AIRPORT" },
  { iata: "FEN", name: "Fernando de Noronha", city: "Fernando de Noronha", country: "BR", subType: "AIRPORT" },
  { iata: "CFB", name: "Cabo Frio Intl", city: "Cabo Frio", country: "BR", subType: "AIRPORT" },
  { iata: "GVR", name: "Governador Valadares", city: "Governador Valadares", country: "BR", subType: "AIRPORT" },
  { iata: "CAW", name: "Bartolomeu Lisandro", city: "Campos dos Goytacazes", country: "BR", subType: "AIRPORT" },
  { iata: "SOD", name: "Sorocaba", city: "Sorocaba", country: "BR", subType: "AIRPORT" },
  { iata: "TBT", name: "Tabatinga", city: "Tabatinga", country: "BR", subType: "AIRPORT" },
  { iata: "TFF", name: "Tefé", city: "Tefé", country: "BR", subType: "AIRPORT" },
  { iata: "MAB", name: "Marabá", city: "Marabá", country: "BR", subType: "AIRPORT" },
  { iata: "CKS", name: "Carajás", city: "Parauapebas", country: "BR", subType: "AIRPORT" },

  // ===== USA =====
  { iata: "MIA", name: "Miami Intl", city: "Miami", country: "US", subType: "AIRPORT" },
  { iata: "MCO", name: "Orlando Intl", city: "Orlando", country: "US", subType: "AIRPORT" },
  { iata: "JFK", name: "John F. Kennedy Intl", city: "New York", country: "US", subType: "AIRPORT" },
  { iata: "EWR", name: "Newark Liberty Intl", city: "Newark", country: "US", subType: "AIRPORT" },
  { iata: "LGA", name: "LaGuardia", city: "New York", country: "US", subType: "AIRPORT" },
  { iata: "LAX", name: "Los Angeles Intl", city: "Los Angeles", country: "US", subType: "AIRPORT" },
  { iata: "SFO", name: "San Francisco Intl", city: "San Francisco", country: "US", subType: "AIRPORT" },
  { iata: "BOS", name: "Logan Intl", city: "Boston", country: "US", subType: "AIRPORT" },
  { iata: "ATL", name: "Hartsfield-Jackson Intl", city: "Atlanta", country: "US", subType: "AIRPORT" },
  { iata: "ORD", name: "O'Hare Intl", city: "Chicago", country: "US", subType: "AIRPORT" },
  { iata: "MDW", name: "Midway Intl", city: "Chicago", country: "US", subType: "AIRPORT" },
  { iata: "DFW", name: "Dallas/Fort Worth Intl", city: "Dallas", country: "US", subType: "AIRPORT" },
  { iata: "IAH", name: "George Bush Intercontinental", city: "Houston", country: "US", subType: "AIRPORT" },
  { iata: "HOU", name: "William P. Hobby", city: "Houston", country: "US", subType: "AIRPORT" },
  { iata: "SEA", name: "Seattle-Tacoma Intl", city: "Seattle", country: "US", subType: "AIRPORT" },
  { iata: "LAS", name: "Harry Reid Intl", city: "Las Vegas", country: "US", subType: "AIRPORT" },
  { iata: "PHX", name: "Phoenix Sky Harbor Intl", city: "Phoenix", country: "US", subType: "AIRPORT" },
  { iata: "DEN", name: "Denver Intl", city: "Denver", country: "US", subType: "AIRPORT" },
  { iata: "IAD", name: "Washington Dulles Intl", city: "Washington", country: "US", subType: "AIRPORT" },
  { iata: "DCA", name: "Ronald Reagan National", city: "Washington", country: "US", subType: "AIRPORT" },
  { iata: "BWI", name: "Baltimore/Washington Intl", city: "Baltimore", country: "US", subType: "AIRPORT" },
  { iata: "SAN", name: "San Diego Intl", city: "San Diego", country: "US", subType: "AIRPORT" },
  { iata: "TPA", name: "Tampa Intl", city: "Tampa", country: "US", subType: "AIRPORT" },
  { iata: "FLL", name: "Fort Lauderdale-Hollywood Intl", city: "Fort Lauderdale", country: "US", subType: "AIRPORT" },
  { iata: "MSP", name: "Minneapolis-St. Paul Intl", city: "Minneapolis", country: "US", subType: "AIRPORT" },
  { iata: "DTW", name: "Detroit Metro Wayne County", city: "Detroit", country: "US", subType: "AIRPORT" },
  { iata: "PHL", name: "Philadelphia Intl", city: "Philadelphia", country: "US", subType: "AIRPORT" },
  { iata: "CLT", name: "Charlotte Douglas Intl", city: "Charlotte", country: "US", subType: "AIRPORT" },
  { iata: "SLC", name: "Salt Lake City Intl", city: "Salt Lake City", country: "US", subType: "AIRPORT" },
  { iata: "PDX", name: "Portland Intl", city: "Portland", country: "US", subType: "AIRPORT" },
  { iata: "RDU", name: "Raleigh-Durham Intl", city: "Raleigh", country: "US", subType: "AIRPORT" },
  { iata: "AUS", name: "Austin-Bergstrom Intl", city: "Austin", country: "US", subType: "AIRPORT" },
  { iata: "SAT", name: "San Antonio Intl", city: "San Antonio", country: "US", subType: "AIRPORT" },
  { iata: "BNA", name: "Nashville Intl", city: "Nashville", country: "US", subType: "AIRPORT" },
  { iata: "MSY", name: "Louis Armstrong New Orleans Intl", city: "New Orleans", country: "US", subType: "AIRPORT" },
  { iata: "STL", name: "St. Louis Lambert Intl", city: "St. Louis", country: "US", subType: "AIRPORT" },
  { iata: "MCI", name: "Kansas City Intl", city: "Kansas City", country: "US", subType: "AIRPORT" },
  { iata: "CLE", name: "Cleveland Hopkins Intl", city: "Cleveland", country: "US", subType: "AIRPORT" },
  { iata: "PIT", name: "Pittsburgh Intl", city: "Pittsburgh", country: "US", subType: "AIRPORT" },
  { iata: "IND", name: "Indianapolis Intl", city: "Indianapolis", country: "US", subType: "AIRPORT" },
  { iata: "CMH", name: "John Glenn Columbus Intl", city: "Columbus", country: "US", subType: "AIRPORT" },
  { iata: "MKE", name: "General Mitchell Intl", city: "Milwaukee", country: "US", subType: "AIRPORT" },
  { iata: "OAK", name: "Oakland Intl", city: "Oakland", country: "US", subType: "AIRPORT" },
  { iata: "SJC", name: "San Jose Intl", city: "San Jose", country: "US", subType: "AIRPORT" },
  { iata: "HNL", name: "Daniel K. Inouye Intl", city: "Honolulu", country: "US", subType: "AIRPORT" },
  { iata: "OGG", name: "Kahului", city: "Maui", country: "US", subType: "AIRPORT" },
  { iata: "ANC", name: "Ted Stevens Anchorage Intl", city: "Anchorage", country: "US", subType: "AIRPORT" },
  { iata: "JAX", name: "Jacksonville Intl", city: "Jacksonville", country: "US", subType: "AIRPORT" },
  { iata: "RSW", name: "Southwest Florida Intl", city: "Fort Myers", country: "US", subType: "AIRPORT" },
  { iata: "PBI", name: "Palm Beach Intl", city: "West Palm Beach", country: "US", subType: "AIRPORT" },
  { iata: "SRQ", name: "Sarasota–Bradenton Intl", city: "Sarasota", country: "US", subType: "AIRPORT" },
  { iata: "BUF", name: "Buffalo Niagara Intl", city: "Buffalo", country: "US", subType: "AIRPORT" },
  { iata: "SYR", name: "Syracuse Hancock Intl", city: "Syracuse", country: "US", subType: "AIRPORT" },
  { iata: "ABQ", name: "Albuquerque Intl Sunport", city: "Albuquerque", country: "US", subType: "AIRPORT" },
  { iata: "OMA", name: "Eppley Airfield", city: "Omaha", country: "US", subType: "AIRPORT" },
  { iata: "RNO", name: "Reno-Tahoe Intl", city: "Reno", country: "US", subType: "AIRPORT" },
  { iata: "BDL", name: "Bradley Intl", city: "Hartford", country: "US", subType: "AIRPORT" },
  { iata: "RIC", name: "Richmond Intl", city: "Richmond", country: "US", subType: "AIRPORT" },
  { iata: "ORF", name: "Norfolk Intl", city: "Norfolk", country: "US", subType: "AIRPORT" },
  { iata: "TUS", name: "Tucson Intl", city: "Tucson", country: "US", subType: "AIRPORT" },

  // ===== CANADA =====
  { iata: "YYZ", name: "Toronto Pearson Intl", city: "Toronto", country: "CA", subType: "AIRPORT" },
  { iata: "YVR", name: "Vancouver Intl", city: "Vancouver", country: "CA", subType: "AIRPORT" },
  { iata: "YUL", name: "Montréal-Trudeau Intl", city: "Montreal", country: "CA", subType: "AIRPORT" },
  { iata: "YYC", name: "Calgary Intl", city: "Calgary", country: "CA", subType: "AIRPORT" },
  { iata: "YEG", name: "Edmonton Intl", city: "Edmonton", country: "CA", subType: "AIRPORT" },
  { iata: "YOW", name: "Ottawa Macdonald-Cartier Intl", city: "Ottawa", country: "CA", subType: "AIRPORT" },
  { iata: "YWG", name: "Winnipeg Richardson Intl", city: "Winnipeg", country: "CA", subType: "AIRPORT" },
  { iata: "YHZ", name: "Halifax Stanfield Intl", city: "Halifax", country: "CA", subType: "AIRPORT" },
  { iata: "YQB", name: "Québec City Jean Lesage Intl", city: "Quebec City", country: "CA", subType: "AIRPORT" },

  // ===== MEXICO & CENTRAL AMERICA =====
  { iata: "MEX", name: "Benito Juárez Intl", city: "Cidade do México", country: "MX", subType: "AIRPORT" },
  { iata: "CUN", name: "Cancún Intl", city: "Cancún", country: "MX", subType: "AIRPORT" },
  { iata: "GDL", name: "Miguel Hidalgo y Costilla Intl", city: "Guadalajara", country: "MX", subType: "AIRPORT" },
  { iata: "MTY", name: "Monterrey Intl", city: "Monterrey", country: "MX", subType: "AIRPORT" },
  { iata: "SJD", name: "Los Cabos Intl", city: "San José del Cabo", country: "MX", subType: "AIRPORT" },
  { iata: "PVR", name: "Gustavo Díaz Ordaz Intl", city: "Puerto Vallarta", country: "MX", subType: "AIRPORT" },
  { iata: "TIJ", name: "Tijuana Intl", city: "Tijuana", country: "MX", subType: "AIRPORT" },
  { iata: "PTY", name: "Tocumen Intl", city: "Panamá", country: "PA", subType: "AIRPORT" },
  { iata: "SJO", name: "Juan Santamaría Intl", city: "San José", country: "CR", subType: "AIRPORT" },
  { iata: "LIR", name: "Daniel Oduber Quirós Intl", city: "Liberia", country: "CR", subType: "AIRPORT" },
  { iata: "SAL", name: "Óscar Arnulfo Romero Intl", city: "San Salvador", country: "SV", subType: "AIRPORT" },
  { iata: "GUA", name: "La Aurora Intl", city: "Cidade da Guatemala", country: "GT", subType: "AIRPORT" },
  { iata: "BZE", name: "Philip S.W. Goldson Intl", city: "Belize City", country: "BZ", subType: "AIRPORT" },
  { iata: "TGU", name: "Toncontín Intl", city: "Tegucigalpa", country: "HN", subType: "AIRPORT" },
  { iata: "MGA", name: "Augusto C. Sandino Intl", city: "Managua", country: "NI", subType: "AIRPORT" },

  // ===== CARIBBEAN =====
  { iata: "PUJ", name: "Punta Cana Intl", city: "Punta Cana", country: "DO", subType: "AIRPORT" },
  { iata: "SDQ", name: "Las Américas Intl", city: "Santo Domingo", country: "DO", subType: "AIRPORT" },
  { iata: "SXM", name: "Princess Juliana Intl", city: "St. Maarten", country: "SX", subType: "AIRPORT" },
  { iata: "AUA", name: "Queen Beatrix Intl", city: "Aruba", country: "AW", subType: "AIRPORT" },
  { iata: "CUR", name: "Hato Intl", city: "Curaçao", country: "CW", subType: "AIRPORT" },
  { iata: "NAS", name: "Lynden Pindling Intl", city: "Nassau", country: "BS", subType: "AIRPORT" },
  { iata: "MBJ", name: "Sangster Intl", city: "Montego Bay", country: "JM", subType: "AIRPORT" },
  { iata: "KIN", name: "Norman Manley Intl", city: "Kingston", country: "JM", subType: "AIRPORT" },
  { iata: "HAV", name: "José Martí Intl", city: "Havana", country: "CU", subType: "AIRPORT" },
  { iata: "VRA", name: "Juan Gualberto Gómez", city: "Varadero", country: "CU", subType: "AIRPORT" },
  { iata: "SJU", name: "Luis Muñoz Marín Intl", city: "San Juan", country: "PR", subType: "AIRPORT" },
  { iata: "BGI", name: "Grantley Adams Intl", city: "Bridgetown", country: "BB", subType: "AIRPORT" },
  { iata: "UVF", name: "Hewanorra Intl", city: "Vieux Fort", country: "LC", subType: "AIRPORT" },
  { iata: "POS", name: "Piarco Intl", city: "Port of Spain", country: "TT", subType: "AIRPORT" },
  { iata: "BON", name: "Flamingo Intl", city: "Bonaire", country: "BQ", subType: "AIRPORT" },
  { iata: "GCM", name: "Owen Roberts Intl", city: "Grand Cayman", country: "KY", subType: "AIRPORT" },
  { iata: "PTP", name: "Pointe-à-Pitre Intl", city: "Pointe-à-Pitre", country: "GP", subType: "AIRPORT" },
  { iata: "FDF", name: "Aimé Césaire Intl", city: "Fort-de-France", country: "MQ", subType: "AIRPORT" },
  { iata: "STT", name: "Cyril E. King", city: "St. Thomas", country: "VI", subType: "AIRPORT" },
  { iata: "POP", name: "Gregorio Luperón Intl", city: "Puerto Plata", country: "DO", subType: "AIRPORT" },
  { iata: "LRM", name: "La Romana Intl", city: "La Romana", country: "DO", subType: "AIRPORT" },
  { iata: "STI", name: "Cibao Intl", city: "Santiago de los Caballeros", country: "DO", subType: "AIRPORT" },


  // ===== SOUTH AMERICA =====
  { iata: "EZE", name: "Ministro Pistarini (Ezeiza)", city: "Buenos Aires", country: "AR", subType: "AIRPORT" },
  { iata: "AEP", name: "Jorge Newbery (Aeroparque)", city: "Buenos Aires", country: "AR", subType: "AIRPORT" },
  { iata: "COR", name: "Ing. Ambrosio Taravella", city: "Córdoba", country: "AR", subType: "AIRPORT" },
  { iata: "MDZ", name: "Gov. Francisco Gabrielli", city: "Mendoza", country: "AR", subType: "AIRPORT" },
  { iata: "BRC", name: "Tte. Luis Candelaria", city: "Bariloche", country: "AR", subType: "AIRPORT" },
  { iata: "IGR", name: "Cataratas del Iguazú", city: "Puerto Iguazú", country: "AR", subType: "AIRPORT" },
  { iata: "USH", name: "Malvinas Argentinas", city: "Ushuaia", country: "AR", subType: "AIRPORT" },
  { iata: "FTE", name: "El Calafate", city: "El Calafate", country: "AR", subType: "AIRPORT" },
  { iata: "SCL", name: "Arturo Merino Benítez Intl", city: "Santiago", country: "CL", subType: "AIRPORT" },
  { iata: "IPC", name: "Mataveri Intl", city: "Isla de Pascua", country: "CL", subType: "AIRPORT" },
  { iata: "PUQ", name: "Pres. Carlos Ibáñez", city: "Punta Arenas", country: "CL", subType: "AIRPORT" },
  { iata: "LIM", name: "Jorge Chávez Intl", city: "Lima", country: "PE", subType: "AIRPORT" },
  { iata: "CUZ", name: "Alejandro Velasco Astete", city: "Cusco", country: "PE", subType: "AIRPORT" },
  { iata: "BOG", name: "El Dorado Intl", city: "Bogotá", country: "CO", subType: "AIRPORT" },
  { iata: "MDE", name: "José María Córdova Intl", city: "Medellín", country: "CO", subType: "AIRPORT" },
  { iata: "CTG", name: "Rafael Núñez Intl", city: "Cartagena", country: "CO", subType: "AIRPORT" },
  { iata: "CLO", name: "Alfonso Bonilla Aragón Intl", city: "Cali", country: "CO", subType: "AIRPORT" },
  { iata: "MVD", name: "Carrasco Intl", city: "Montevidéu", country: "UY", subType: "AIRPORT" },
  { iata: "PDP", name: "Capitán Corbeta C.A. Curbelo", city: "Punta del Este", country: "UY", subType: "AIRPORT" },
  { iata: "ADZ", name: "Gustavo Rojas Pinilla", city: "San Andrés", country: "CO", subType: "AIRPORT" },
  { iata: "SLA", name: "Martín Miguel de Güemes", city: "Salta", country: "AR", subType: "AIRPORT" },
  { iata: "AGT", name: "Guaraní Intl", city: "Ciudad del Este", country: "PY", subType: "AIRPORT" },
  { iata: "UIO", name: "Mariscal Sucre Intl", city: "Quito", country: "EC", subType: "AIRPORT" },
  { iata: "GYE", name: "José Joaquín de Olmedo Intl", city: "Guayaquil", country: "EC", subType: "AIRPORT" },
  { iata: "GPS", name: "Seymour", city: "Galápagos", country: "EC", subType: "AIRPORT" },
  { iata: "CCS", name: "Simón Bolívar Intl", city: "Caracas", country: "VE", subType: "AIRPORT" },
  { iata: "ASU", name: "Silvio Pettirossi Intl", city: "Assunção", country: "PY", subType: "AIRPORT" },
  { iata: "VVI", name: "Viru Viru Intl", city: "Santa Cruz", country: "BO", subType: "AIRPORT" },
  { iata: "LPB", name: "El Alto Intl", city: "La Paz", country: "BO", subType: "AIRPORT" },
  { iata: "GEO", name: "Cheddi Jagan Intl", city: "Georgetown", country: "GY", subType: "AIRPORT" },
  { iata: "PBM", name: "Johan Adolf Pengel Intl", city: "Paramaribo", country: "SR", subType: "AIRPORT" },
  { iata: "CAY", name: "Félix Eboué", city: "Cayenne", country: "GF", subType: "AIRPORT" },

  // ===== EUROPE — PORTUGAL & SPAIN =====
  { iata: "LIS", name: "Humberto Delgado", city: "Lisboa", country: "PT", subType: "AIRPORT" },
  { iata: "OPO", name: "Francisco Sá Carneiro", city: "Porto", country: "PT", subType: "AIRPORT" },
  { iata: "FAO", name: "Faro", city: "Faro", country: "PT", subType: "AIRPORT" },
  { iata: "FNC", name: "Cristiano Ronaldo Intl", city: "Funchal", country: "PT", subType: "AIRPORT" },
  { iata: "PDL", name: "João Paulo II", city: "Ponta Delgada", country: "PT", subType: "AIRPORT" },
  { iata: "MAD", name: "Adolfo Suárez Madrid–Barajas", city: "Madri", country: "ES", subType: "AIRPORT" },
  { iata: "BCN", name: "Josep Tarradellas Barcelona-El Prat", city: "Barcelona", country: "ES", subType: "AIRPORT" },
  { iata: "PMI", name: "Palma de Mallorca", city: "Palma de Mallorca", country: "ES", subType: "AIRPORT" },
  { iata: "AGP", name: "Málaga-Costa del Sol", city: "Málaga", country: "ES", subType: "AIRPORT" },
  { iata: "ALC", name: "Alicante-Elche", city: "Alicante", country: "ES", subType: "AIRPORT" },
  { iata: "IBZ", name: "Ibiza", city: "Ibiza", country: "ES", subType: "AIRPORT" },
  { iata: "TFS", name: "Tenerife Sur", city: "Tenerife", country: "ES", subType: "AIRPORT" },
  { iata: "LPA", name: "Gran Canaria", city: "Las Palmas", country: "ES", subType: "AIRPORT" },
  { iata: "SVQ", name: "Sevilla", city: "Sevilla", country: "ES", subType: "AIRPORT" },
  { iata: "VLC", name: "Valencia", city: "Valencia", country: "ES", subType: "AIRPORT" },
  { iata: "BIO", name: "Bilbao", city: "Bilbao", country: "ES", subType: "AIRPORT" },

  // ===== EUROPE — FRANCE =====
  { iata: "CDG", name: "Charles de Gaulle", city: "Paris", country: "FR", subType: "AIRPORT" },
  { iata: "ORY", name: "Paris-Orly", city: "Paris", country: "FR", subType: "AIRPORT" },
  { iata: "NCE", name: "Nice Côte d'Azur", city: "Nice", country: "FR", subType: "AIRPORT" },
  { iata: "LYS", name: "Lyon-Saint Exupéry", city: "Lyon", country: "FR", subType: "AIRPORT" },
  { iata: "MRS", name: "Marseille Provence", city: "Marseille", country: "FR", subType: "AIRPORT" },
  { iata: "TLS", name: "Toulouse-Blagnac", city: "Toulouse", country: "FR", subType: "AIRPORT" },
  { iata: "BOD", name: "Bordeaux-Mérignac", city: "Bordeaux", country: "FR", subType: "AIRPORT" },

  // ===== EUROPE — ITALY =====
  { iata: "FCO", name: "Leonardo da Vinci (Fiumicino)", city: "Roma", country: "IT", subType: "AIRPORT" },
  { iata: "CIA", name: "Ciampino", city: "Roma", country: "IT", subType: "AIRPORT" },
  { iata: "MXP", name: "Malpensa", city: "Milão", country: "IT", subType: "AIRPORT" },
  { iata: "LIN", name: "Linate", city: "Milão", country: "IT", subType: "AIRPORT" },
  { iata: "NAP", name: "Capodichino", city: "Nápoles", country: "IT", subType: "AIRPORT" },
  { iata: "VCE", name: "Marco Polo", city: "Veneza", country: "IT", subType: "AIRPORT" },
  { iata: "FLR", name: "Amerigo Vespucci", city: "Florença", country: "IT", subType: "AIRPORT" },
  { iata: "PSA", name: "Galileo Galilei", city: "Pisa", country: "IT", subType: "AIRPORT" },
  { iata: "BLQ", name: "Guglielmo Marconi", city: "Bolonha", country: "IT", subType: "AIRPORT" },
  { iata: "CTA", name: "Catania-Fontanarossa", city: "Catania", country: "IT", subType: "AIRPORT" },
  { iata: "PMO", name: "Falcone Borsellino", city: "Palermo", country: "IT", subType: "AIRPORT" },
  { iata: "TRN", name: "Caselle", city: "Turim", country: "IT", subType: "AIRPORT" },

  // ===== EUROPE — UK & IRELAND =====
  { iata: "LHR", name: "Heathrow", city: "Londres", country: "GB", subType: "AIRPORT" },
  { iata: "LGW", name: "Gatwick", city: "Londres", country: "GB", subType: "AIRPORT" },
  { iata: "STN", name: "Stansted", city: "Londres", country: "GB", subType: "AIRPORT" },
  { iata: "LTN", name: "Luton", city: "Londres", country: "GB", subType: "AIRPORT" },
  { iata: "LCY", name: "London City", city: "Londres", country: "GB", subType: "AIRPORT" },
  { iata: "MAN", name: "Manchester", city: "Manchester", country: "GB", subType: "AIRPORT" },
  { iata: "EDI", name: "Edinburgh", city: "Edimburgo", country: "GB", subType: "AIRPORT" },
  { iata: "GLA", name: "Glasgow", city: "Glasgow", country: "GB", subType: "AIRPORT" },
  { iata: "BHX", name: "Birmingham", city: "Birmingham", country: "GB", subType: "AIRPORT" },
  { iata: "BRS", name: "Bristol", city: "Bristol", country: "GB", subType: "AIRPORT" },
  { iata: "DUB", name: "Dublin", city: "Dublin", country: "IE", subType: "AIRPORT" },

  // ===== EUROPE — GERMANY =====
  { iata: "FRA", name: "Frankfurt am Main", city: "Frankfurt", country: "DE", subType: "AIRPORT" },
  { iata: "MUC", name: "Franz Josef Strauss", city: "Munique", country: "DE", subType: "AIRPORT" },
  { iata: "BER", name: "Berlin Brandenburg", city: "Berlim", country: "DE", subType: "AIRPORT" },
  { iata: "DUS", name: "Düsseldorf", city: "Düsseldorf", country: "DE", subType: "AIRPORT" },
  { iata: "HAM", name: "Hamburg", city: "Hamburgo", country: "DE", subType: "AIRPORT" },
  { iata: "STR", name: "Stuttgart", city: "Stuttgart", country: "DE", subType: "AIRPORT" },
  { iata: "CGN", name: "Cologne Bonn", city: "Colônia", country: "DE", subType: "AIRPORT" },
  { iata: "HAJ", name: "Hannover", city: "Hannover", country: "DE", subType: "AIRPORT" },
  { iata: "NUE", name: "Nuremberg", city: "Nuremberg", country: "DE", subType: "AIRPORT" },

  // ===== EUROPE — NETHERLANDS, BELGIUM, SWITZERLAND =====
  { iata: "AMS", name: "Schiphol", city: "Amsterdã", country: "NL", subType: "AIRPORT" },
  { iata: "BRU", name: "Brussels", city: "Bruxelas", country: "BE", subType: "AIRPORT" },
  { iata: "ZRH", name: "Zürich", city: "Zurique", country: "CH", subType: "AIRPORT" },
  { iata: "GVA", name: "Genève", city: "Genebra", country: "CH", subType: "AIRPORT" },
  { iata: "BSL", name: "EuroAirport Basel-Mulhouse", city: "Basileia", country: "CH", subType: "AIRPORT" },
  { iata: "LUX", name: "Luxembourg", city: "Luxemburgo", country: "LU", subType: "AIRPORT" },

  // ===== EUROPE — SCANDINAVIA =====
  { iata: "CPH", name: "Kastrup", city: "Copenhague", country: "DK", subType: "AIRPORT" },
  { iata: "OSL", name: "Gardermoen", city: "Oslo", country: "NO", subType: "AIRPORT" },
  { iata: "ARN", name: "Arlanda", city: "Estocolmo", country: "SE", subType: "AIRPORT" },
  { iata: "GOT", name: "Landvetter", city: "Gotemburgo", country: "SE", subType: "AIRPORT" },
  { iata: "HEL", name: "Helsinki-Vantaa", city: "Helsinque", country: "FI", subType: "AIRPORT" },
  { iata: "KEF", name: "Keflavík Intl", city: "Reykjavik", country: "IS", subType: "AIRPORT" },
  { iata: "BGO", name: "Bergen Flesland", city: "Bergen", country: "NO", subType: "AIRPORT" },

  // ===== EUROPE — EASTERN =====
  { iata: "WAW", name: "Chopin", city: "Varsóvia", country: "PL", subType: "AIRPORT" },
  { iata: "KRK", name: "John Paul II", city: "Cracóvia", country: "PL", subType: "AIRPORT" },
  { iata: "PRG", name: "Václav Havel", city: "Praga", country: "CZ", subType: "AIRPORT" },
  { iata: "BUD", name: "Ferenc Liszt Intl", city: "Budapeste", country: "HU", subType: "AIRPORT" },
  { iata: "VIE", name: "Vienna Intl", city: "Viena", country: "AT", subType: "AIRPORT" },
  { iata: "OTP", name: "Henri Coandă Intl", city: "Bucareste", country: "RO", subType: "AIRPORT" },
  { iata: "SOF", name: "Sofia", city: "Sófia", country: "BG", subType: "AIRPORT" },
  { iata: "BEG", name: "Nikola Tesla", city: "Belgrado", country: "RS", subType: "AIRPORT" },
  { iata: "ZAG", name: "Franjo Tuđman", city: "Zagreb", country: "HR", subType: "AIRPORT" },
  { iata: "SPU", name: "Split", city: "Split", country: "HR", subType: "AIRPORT" },
  { iata: "DBV", name: "Dubrovnik", city: "Dubrovnik", country: "HR", subType: "AIRPORT" },
  { iata: "LJU", name: "Ljubljana Jože Pučnik", city: "Liubliana", country: "SI", subType: "AIRPORT" },
  { iata: "TLL", name: "Lennart Meri Tallinn", city: "Tallinn", country: "EE", subType: "AIRPORT" },
  { iata: "RIX", name: "Riga Intl", city: "Riga", country: "LV", subType: "AIRPORT" },
  { iata: "VNO", name: "Vilnius Intl", city: "Vilnius", country: "LT", subType: "AIRPORT" },
  { iata: "SKP", name: "Skopje Intl", city: "Skopje", country: "MK", subType: "AIRPORT" },
  { iata: "TIA", name: "Tirana Intl", city: "Tirana", country: "AL", subType: "AIRPORT" },

  // ===== EUROPE — GREECE & TURKEY =====
  { iata: "ATH", name: "Eleftherios Venizelos", city: "Atenas", country: "GR", subType: "AIRPORT" },
  { iata: "SKG", name: "Thessaloniki Macedonia", city: "Tessalônica", country: "GR", subType: "AIRPORT" },
  { iata: "HER", name: "Heraklion Intl", city: "Heráklion", country: "GR", subType: "AIRPORT" },
  { iata: "JMK", name: "Mykonos", city: "Mykonos", country: "GR", subType: "AIRPORT" },
  { iata: "JTR", name: "Santorini (Thira)", city: "Santorini", country: "GR", subType: "AIRPORT" },
  { iata: "RHO", name: "Rhodes Diagoras", city: "Rhodes", country: "GR", subType: "AIRPORT" },
  { iata: "CFU", name: "Corfu Ioannis Kapodistrias", city: "Corfu", country: "GR", subType: "AIRPORT" },
  { iata: "ZTH", name: "Zakynthos Intl", city: "Zakynthos", country: "GR", subType: "AIRPORT" },
  { iata: "IST", name: "Istanbul", city: "Istambul", country: "TR", subType: "AIRPORT" },
  { iata: "SAW", name: "Sabiha Gökçen", city: "Istambul", country: "TR", subType: "AIRPORT" },
  { iata: "ESB", name: "Esenboğa Intl", city: "Ancara", country: "TR", subType: "AIRPORT" },
  { iata: "AYT", name: "Antalya", city: "Antalya", country: "TR", subType: "AIRPORT" },
  { iata: "ADB", name: "Adnan Menderes", city: "Izmir", country: "TR", subType: "AIRPORT" },
  { iata: "DLM", name: "Dalaman", city: "Dalaman", country: "TR", subType: "AIRPORT" },
  { iata: "BJV", name: "Milas-Bodrum", city: "Bodrum", country: "TR", subType: "AIRPORT" },

  // ===== MIDDLE EAST =====
  { iata: "DXB", name: "Dubai Intl", city: "Dubai", country: "AE", subType: "AIRPORT" },
  { iata: "DWC", name: "Al Maktoum Intl", city: "Dubai", country: "AE", subType: "AIRPORT" },
  { iata: "AUH", name: "Abu Dhabi Intl", city: "Abu Dhabi", country: "AE", subType: "AIRPORT" },
  { iata: "SHJ", name: "Sharjah Intl", city: "Sharjah", country: "AE", subType: "AIRPORT" },
  { iata: "DOH", name: "Hamad Intl", city: "Doha", country: "QA", subType: "AIRPORT" },
  { iata: "BAH", name: "Bahrain Intl", city: "Bahrein", country: "BH", subType: "AIRPORT" },
  { iata: "KWI", name: "Kuwait Intl", city: "Kuwait", country: "KW", subType: "AIRPORT" },
  { iata: "MCT", name: "Muscat Intl", city: "Mascate", country: "OM", subType: "AIRPORT" },
  { iata: "JED", name: "King Abdulaziz Intl", city: "Jeddah", country: "SA", subType: "AIRPORT" },
  { iata: "RUH", name: "King Khalid Intl", city: "Riad", country: "SA", subType: "AIRPORT" },
  { iata: "DMM", name: "King Fahd Intl", city: "Dammam", country: "SA", subType: "AIRPORT" },
  { iata: "MED", name: "Prince Mohammad bin Abdulaziz", city: "Medina", country: "SA", subType: "AIRPORT" },
  { iata: "AMM", name: "Queen Alia Intl", city: "Amã", country: "JO", subType: "AIRPORT" },
  { iata: "TLV", name: "Ben Gurion Intl", city: "Tel Aviv", country: "IL", subType: "AIRPORT" },
  { iata: "BEY", name: "Rafic Hariri Intl", city: "Beirute", country: "LB", subType: "AIRPORT" },
  { iata: "BGW", name: "Baghdad Intl", city: "Bagdá", country: "IQ", subType: "AIRPORT" },
  { iata: "EBL", name: "Erbil Intl", city: "Erbil", country: "IQ", subType: "AIRPORT" },
  { iata: "IKA", name: "Imam Khomeini Intl", city: "Teerã", country: "IR", subType: "AIRPORT" },

  // ===== AFRICA — NORTH =====
  { iata: "CAI", name: "Cairo Intl", city: "Cairo", country: "EG", subType: "AIRPORT" },
  { iata: "HRG", name: "Hurghada Intl", city: "Hurghada", country: "EG", subType: "AIRPORT" },
  { iata: "SSH", name: "Sharm el-Sheikh Intl", city: "Sharm el-Sheikh", country: "EG", subType: "AIRPORT" },
  { iata: "LXR", name: "Luxor Intl", city: "Luxor", country: "EG", subType: "AIRPORT" },
  { iata: "CMN", name: "Mohammed V Intl", city: "Casablanca", country: "MA", subType: "AIRPORT" },
  { iata: "RAK", name: "Menara", city: "Marrakech", country: "MA", subType: "AIRPORT" },
  { iata: "TNG", name: "Ibn Battouta", city: "Tânger", country: "MA", subType: "AIRPORT" },
  { iata: "FEZ", name: "Saïss", city: "Fez", country: "MA", subType: "AIRPORT" },
  { iata: "ALG", name: "Houari Boumediene", city: "Argel", country: "DZ", subType: "AIRPORT" },
  { iata: "TUN", name: "Tunis-Carthage Intl", city: "Tunis", country: "TN", subType: "AIRPORT" },

  // ===== AFRICA — SUB-SAHARAN =====
  { iata: "JNB", name: "O.R. Tambo Intl", city: "Joanesburgo", country: "ZA", subType: "AIRPORT" },
  { iata: "CPT", name: "Cape Town Intl", city: "Cidade do Cabo", country: "ZA", subType: "AIRPORT" },
  { iata: "DUR", name: "King Shaka Intl", city: "Durban", country: "ZA", subType: "AIRPORT" },
  { iata: "NBO", name: "Jomo Kenyatta Intl", city: "Nairóbi", country: "KE", subType: "AIRPORT" },
  { iata: "MBA", name: "Moi Intl", city: "Mombasa", country: "KE", subType: "AIRPORT" },
  { iata: "ADD", name: "Bole Intl", city: "Adis Abeba", country: "ET", subType: "AIRPORT" },
  { iata: "LOS", name: "Murtala Muhammed Intl", city: "Lagos", country: "NG", subType: "AIRPORT" },
  { iata: "ABV", name: "Nnamdi Azikiwe Intl", city: "Abuja", country: "NG", subType: "AIRPORT" },
  { iata: "ACC", name: "Kotoka Intl", city: "Acra", country: "GH", subType: "AIRPORT" },
  { iata: "DAR", name: "Julius Nyerere Intl", city: "Dar es Salaam", country: "TZ", subType: "AIRPORT" },
  { iata: "ZNZ", name: "Abeid Amani Karume Intl", city: "Zanzibar", country: "TZ", subType: "AIRPORT" },
  { iata: "JRO", name: "Kilimanjaro Intl", city: "Kilimanjaro", country: "TZ", subType: "AIRPORT" },
  { iata: "EBB", name: "Entebbe Intl", city: "Entebbe", country: "UG", subType: "AIRPORT" },
  { iata: "KGL", name: "Kigali Intl", city: "Kigali", country: "RW", subType: "AIRPORT" },
  { iata: "MPM", name: "Maputo Intl", city: "Maputo", country: "MZ", subType: "AIRPORT" },
  { iata: "LUN", name: "Kenneth Kaunda Intl", city: "Lusaka", country: "ZM", subType: "AIRPORT" },
  { iata: "HRE", name: "Robert Gabriel Mugabe Intl", city: "Harare", country: "ZW", subType: "AIRPORT" },
  { iata: "VFA", name: "Victoria Falls", city: "Victoria Falls", country: "ZW", subType: "AIRPORT" },
  { iata: "WDH", name: "Hosea Kutako Intl", city: "Windhoek", country: "NA", subType: "AIRPORT" },
  { iata: "GBE", name: "Sir Seretse Khama Intl", city: "Gaborone", country: "BW", subType: "AIRPORT" },
  { iata: "MRU", name: "Sir Seewoosagur Ramgoolam Intl", city: "Maurício", country: "MU", subType: "AIRPORT" },
  { iata: "SEZ", name: "Seychelles Intl", city: "Mahé", country: "SC", subType: "AIRPORT" },
  { iata: "TNR", name: "Ivato Intl", city: "Antananarivo", country: "MG", subType: "AIRPORT" },
  { iata: "DKR", name: "Blaise Diagne Intl", city: "Dakar", country: "SN", subType: "AIRPORT" },
  { iata: "ABJ", name: "Félix-Houphouët-Boigny Intl", city: "Abidjan", country: "CI", subType: "AIRPORT" },
  { iata: "LFW", name: "Lomé-Tokoin", city: "Lomé", country: "TG", subType: "AIRPORT" },
  { iata: "COO", name: "Cadjehoun", city: "Cotonou", country: "BJ", subType: "AIRPORT" },
  { iata: "OUA", name: "Ouagadougou", city: "Ouagadougou", country: "BF", subType: "AIRPORT" },
  { iata: "BKO", name: "Modibo Keïta Intl", city: "Bamako", country: "ML", subType: "AIRPORT" },
  { iata: "NKC", name: "Nouakchott-Oumtounsy Intl", city: "Nouakchott", country: "MR", subType: "AIRPORT" },
  { iata: "CMR", name: "Colmar-Houssen", city: "Colmar", country: "FR", subType: "AIRPORT" },
  { iata: "DLA", name: "Douala Intl", city: "Douala", country: "CM", subType: "AIRPORT" },
  { iata: "LBV", name: "Léon-Mba Intl", city: "Libreville", country: "GA", subType: "AIRPORT" },
  { iata: "FIH", name: "N'Djili Intl", city: "Kinshasa", country: "CD", subType: "AIRPORT" },
  { iata: "BZV", name: "Maya-Maya", city: "Brazzaville", country: "CG", subType: "AIRPORT" },
  { iata: "LAD", name: "Quatro de Fevereiro", city: "Luanda", country: "AO", subType: "AIRPORT" },

  // ===== ASIA — EAST =====
  { iata: "NRT", name: "Narita Intl", city: "Tóquio", country: "JP", subType: "AIRPORT" },
  { iata: "HND", name: "Haneda", city: "Tóquio", country: "JP", subType: "AIRPORT" },
  { iata: "KIX", name: "Kansai Intl", city: "Osaka", country: "JP", subType: "AIRPORT" },
  { iata: "ITM", name: "Itami", city: "Osaka", country: "JP", subType: "AIRPORT" },
  { iata: "NGO", name: "Chubu Centrair Intl", city: "Nagoia", country: "JP", subType: "AIRPORT" },
  { iata: "FUK", name: "Fukuoka", city: "Fukuoka", country: "JP", subType: "AIRPORT" },
  { iata: "CTS", name: "New Chitose", city: "Sapporo", country: "JP", subType: "AIRPORT" },
  { iata: "OKA", name: "Naha", city: "Okinawa", country: "JP", subType: "AIRPORT" },
  { iata: "ICN", name: "Incheon Intl", city: "Seul", country: "KR", subType: "AIRPORT" },
  { iata: "GMP", name: "Gimpo Intl", city: "Seul", country: "KR", subType: "AIRPORT" },
  { iata: "PUS", name: "Gimhae Intl", city: "Busan", country: "KR", subType: "AIRPORT" },
  { iata: "CJU", name: "Jeju Intl", city: "Jeju", country: "KR", subType: "AIRPORT" },
  { iata: "PEK", name: "Capital Intl", city: "Pequim", country: "CN", subType: "AIRPORT" },
  { iata: "PKX", name: "Daxing Intl", city: "Pequim", country: "CN", subType: "AIRPORT" },
  { iata: "PVG", name: "Pudong Intl", city: "Xangai", country: "CN", subType: "AIRPORT" },
  { iata: "SHA", name: "Hongqiao Intl", city: "Xangai", country: "CN", subType: "AIRPORT" },
  { iata: "CAN", name: "Baiyun Intl", city: "Guangzhou", country: "CN", subType: "AIRPORT" },
  { iata: "SZX", name: "Bao'an Intl", city: "Shenzhen", country: "CN", subType: "AIRPORT" },
  { iata: "CTU", name: "Tianfu Intl", city: "Chengdu", country: "CN", subType: "AIRPORT" },
  { iata: "CKG", name: "Jiangbei Intl", city: "Chongqing", country: "CN", subType: "AIRPORT" },
  { iata: "XMN", name: "Gaoqi Intl", city: "Xiamen", country: "CN", subType: "AIRPORT" },
  { iata: "KMG", name: "Changshui Intl", city: "Kunming", country: "CN", subType: "AIRPORT" },
  { iata: "WUH", name: "Tianhe Intl", city: "Wuhan", country: "CN", subType: "AIRPORT" },
  { iata: "HGH", name: "Xiaoshan Intl", city: "Hangzhou", country: "CN", subType: "AIRPORT" },
  { iata: "NKG", name: "Lukou Intl", city: "Nanjing", country: "CN", subType: "AIRPORT" },
  { iata: "XIY", name: "Xianyang Intl", city: "Xi'an", country: "CN", subType: "AIRPORT" },
  { iata: "TSN", name: "Binhai Intl", city: "Tianjin", country: "CN", subType: "AIRPORT" },
  { iata: "DLC", name: "Zhoushuizi Intl", city: "Dalian", country: "CN", subType: "AIRPORT" },
  { iata: "HAK", name: "Meilan Intl", city: "Haikou", country: "CN", subType: "AIRPORT" },
  { iata: "SYX", name: "Phoenix Intl", city: "Sanya", country: "CN", subType: "AIRPORT" },
  { iata: "HKG", name: "Hong Kong Intl", city: "Hong Kong", country: "HK", subType: "AIRPORT" },
  { iata: "MFM", name: "Macau Intl", city: "Macau", country: "MO", subType: "AIRPORT" },
  { iata: "TPE", name: "Taoyuan Intl", city: "Taipei", country: "TW", subType: "AIRPORT" },
  { iata: "TSA", name: "Songshan", city: "Taipei", country: "TW", subType: "AIRPORT" },
  { iata: "ULN", name: "Chinggis Khaan Intl", city: "Ulaanbaatar", country: "MN", subType: "AIRPORT" },

  // ===== ASIA — SOUTHEAST =====
  { iata: "SIN", name: "Changi", city: "Singapura", country: "SG", subType: "AIRPORT" },
  { iata: "BKK", name: "Suvarnabhumi", city: "Bangkok", country: "TH", subType: "AIRPORT" },
  { iata: "DMK", name: "Don Mueang", city: "Bangkok", country: "TH", subType: "AIRPORT" },
  { iata: "HKT", name: "Phuket Intl", city: "Phuket", country: "TH", subType: "AIRPORT" },
  { iata: "CNX", name: "Chiang Mai Intl", city: "Chiang Mai", country: "TH", subType: "AIRPORT" },
  { iata: "KBV", name: "Krabi", city: "Krabi", country: "TH", subType: "AIRPORT" },
  { iata: "USM", name: "Koh Samui", city: "Koh Samui", country: "TH", subType: "AIRPORT" },
  { iata: "KUL", name: "Kuala Lumpur Intl", city: "Kuala Lumpur", country: "MY", subType: "AIRPORT" },
  { iata: "PEN", name: "Penang Intl", city: "Penang", country: "MY", subType: "AIRPORT" },
  { iata: "BKI", name: "Kota Kinabalu Intl", city: "Kota Kinabalu", country: "MY", subType: "AIRPORT" },
  { iata: "LGK", name: "Langkawi Intl", city: "Langkawi", country: "MY", subType: "AIRPORT" },
  { iata: "CGK", name: "Soekarno-Hatta Intl", city: "Jacarta", country: "ID", subType: "AIRPORT" },
  { iata: "DPS", name: "Ngurah Rai Intl", city: "Bali", country: "ID", subType: "AIRPORT" },
  { iata: "SUB", name: "Juanda Intl", city: "Surabaya", country: "ID", subType: "AIRPORT" },
  { iata: "JOG", name: "Adisucipto Intl", city: "Yogyakarta", country: "ID", subType: "AIRPORT" },
  { iata: "UPG", name: "Sultan Hasanuddin Intl", city: "Makassar", country: "ID", subType: "AIRPORT" },
  { iata: "MNL", name: "Ninoy Aquino Intl", city: "Manila", country: "PH", subType: "AIRPORT" },
  { iata: "CEB", name: "Mactan-Cebu Intl", city: "Cebu", country: "PH", subType: "AIRPORT" },
  { iata: "SGN", name: "Tan Son Nhat Intl", city: "Ho Chi Minh", country: "VN", subType: "AIRPORT" },
  { iata: "HAN", name: "Noi Bai Intl", city: "Hanoi", country: "VN", subType: "AIRPORT" },
  { iata: "DAD", name: "Da Nang Intl", city: "Da Nang", country: "VN", subType: "AIRPORT" },
  { iata: "PQC", name: "Phu Quoc Intl", city: "Phu Quoc", country: "VN", subType: "AIRPORT" },
  { iata: "CXR", name: "Cam Ranh Intl", city: "Nha Trang", country: "VN", subType: "AIRPORT" },
  { iata: "REP", name: "Siem Reap-Angkor Intl", city: "Siem Reap", country: "KH", subType: "AIRPORT" },
  { iata: "PNH", name: "Phnom Penh Intl", city: "Phnom Penh", country: "KH", subType: "AIRPORT" },
  { iata: "RGN", name: "Yangon Intl", city: "Yangon", country: "MM", subType: "AIRPORT" },
  { iata: "VTE", name: "Wattay Intl", city: "Vientiane", country: "LA", subType: "AIRPORT" },
  { iata: "LPQ", name: "Luang Prabang Intl", city: "Luang Prabang", country: "LA", subType: "AIRPORT" },
  { iata: "BWN", name: "Brunei Intl", city: "Bandar Seri Begawan", country: "BN", subType: "AIRPORT" },

  // ===== ASIA — SOUTH =====
  { iata: "DEL", name: "Indira Gandhi Intl", city: "Nova Delhi", country: "IN", subType: "AIRPORT" },
  { iata: "BOM", name: "Chhatrapati Shivaji Maharaj Intl", city: "Mumbai", country: "IN", subType: "AIRPORT" },
  { iata: "BLR", name: "Kempegowda Intl", city: "Bangalore", country: "IN", subType: "AIRPORT" },
  { iata: "MAA", name: "Chennai Intl", city: "Chennai", country: "IN", subType: "AIRPORT" },
  { iata: "HYD", name: "Rajiv Gandhi Intl", city: "Hyderabad", country: "IN", subType: "AIRPORT" },
  { iata: "CCU", name: "Netaji Subhas Chandra Bose Intl", city: "Kolkata", country: "IN", subType: "AIRPORT" },
  { iata: "COK", name: "Cochin Intl", city: "Kochi", country: "IN", subType: "AIRPORT" },
  { iata: "GOI", name: "Goa Intl", city: "Goa", country: "IN", subType: "AIRPORT" },
  { iata: "AMD", name: "Sardar Vallabhbhai Patel Intl", city: "Ahmedabad", country: "IN", subType: "AIRPORT" },
  { iata: "JAI", name: "Jaipur Intl", city: "Jaipur", country: "IN", subType: "AIRPORT" },
  { iata: "TRV", name: "Trivandrum Intl", city: "Thiruvananthapuram", country: "IN", subType: "AIRPORT" },
  { iata: "PNQ", name: "Pune", city: "Pune", country: "IN", subType: "AIRPORT" },
  { iata: "LKO", name: "Chaudhary Charan Singh Intl", city: "Lucknow", country: "IN", subType: "AIRPORT" },
  { iata: "AGR", name: "Agra", city: "Agra", country: "IN", subType: "AIRPORT" },
  { iata: "CMB", name: "Bandaranaike Intl", city: "Colombo", country: "LK", subType: "AIRPORT" },
  { iata: "MLE", name: "Velana Intl", city: "Malé", country: "MV", subType: "AIRPORT" },
  { iata: "KTM", name: "Tribhuvan Intl", city: "Katmandu", country: "NP", subType: "AIRPORT" },
  { iata: "DAC", name: "Hazrat Shahjalal Intl", city: "Dhaka", country: "BD", subType: "AIRPORT" },
  { iata: "ISB", name: "Islamabad Intl", city: "Islamabad", country: "PK", subType: "AIRPORT" },
  { iata: "KHI", name: "Jinnah Intl", city: "Karachi", country: "PK", subType: "AIRPORT" },
  { iata: "LHE", name: "Allama Iqbal Intl", city: "Lahore", country: "PK", subType: "AIRPORT" },

  // ===== ASIA — CENTRAL =====
  { iata: "TAS", name: "Islam Karimov Intl", city: "Tashkent", country: "UZ", subType: "AIRPORT" },
  { iata: "ALA", name: "Almaty Intl", city: "Almaty", country: "KZ", subType: "AIRPORT" },
  { iata: "NQZ", name: "Nursultan Nazarbayev Intl", city: "Astana", country: "KZ", subType: "AIRPORT" },
  { iata: "GYD", name: "Heydar Aliyev Intl", city: "Baku", country: "AZ", subType: "AIRPORT" },
  { iata: "TBS", name: "Tbilisi Intl", city: "Tbilisi", country: "GE", subType: "AIRPORT" },
  { iata: "EVN", name: "Zvartnots Intl", city: "Yerevan", country: "AM", subType: "AIRPORT" },

  // ===== RUSSIA & CIS =====
  { iata: "SVO", name: "Sheremetyevo Intl", city: "Moscou", country: "RU", subType: "AIRPORT" },
  { iata: "DME", name: "Domodedovo Intl", city: "Moscou", country: "RU", subType: "AIRPORT" },
  { iata: "VKO", name: "Vnukovo Intl", city: "Moscou", country: "RU", subType: "AIRPORT" },
  { iata: "LED", name: "Pulkovo", city: "São Petersburgo", country: "RU", subType: "AIRPORT" },

  // ===== OCEANIA =====
  { iata: "SYD", name: "Kingsford Smith", city: "Sydney", country: "AU", subType: "AIRPORT" },
  { iata: "MEL", name: "Melbourne (Tullamarine)", city: "Melbourne", country: "AU", subType: "AIRPORT" },
  { iata: "BNE", name: "Brisbane", city: "Brisbane", country: "AU", subType: "AIRPORT" },
  { iata: "PER", name: "Perth", city: "Perth", country: "AU", subType: "AIRPORT" },
  { iata: "ADL", name: "Adelaide", city: "Adelaide", country: "AU", subType: "AIRPORT" },
  { iata: "CBR", name: "Canberra", city: "Canberra", country: "AU", subType: "AIRPORT" },
  { iata: "OOL", name: "Gold Coast", city: "Gold Coast", country: "AU", subType: "AIRPORT" },
  { iata: "CNS", name: "Cairns", city: "Cairns", country: "AU", subType: "AIRPORT" },
  { iata: "DRW", name: "Darwin Intl", city: "Darwin", country: "AU", subType: "AIRPORT" },
  { iata: "HBA", name: "Hobart Intl", city: "Hobart", country: "AU", subType: "AIRPORT" },
  { iata: "AKL", name: "Auckland", city: "Auckland", country: "NZ", subType: "AIRPORT" },
  { iata: "WLG", name: "Wellington", city: "Wellington", country: "NZ", subType: "AIRPORT" },
  { iata: "CHC", name: "Christchurch Intl", city: "Christchurch", country: "NZ", subType: "AIRPORT" },
  { iata: "ZQN", name: "Queenstown", city: "Queenstown", country: "NZ", subType: "AIRPORT" },
  { iata: "NAN", name: "Nadi Intl", city: "Nadi", country: "FJ", subType: "AIRPORT" },
  { iata: "PPT", name: "Faa'a Intl", city: "Papeete", country: "PF", subType: "AIRPORT" },
  { iata: "NOU", name: "La Tontouta Intl", city: "Nouméa", country: "NC", subType: "AIRPORT" },
  { iata: "APW", name: "Faleolo Intl", city: "Apia", country: "WS", subType: "AIRPORT" },
  { iata: "GUM", name: "Antonio B. Won Pat Intl", city: "Guam", country: "GU", subType: "AIRPORT" },
];

/**
 * Search airports locally by IATA code, city name, airport name, or country.
 * Returns up to `limit` results.
 */
export function searchAirportsLocal(keyword: string, limit = 12): AirportEntry[] {
  if (!keyword || keyword.length < 1) return [];
  const q = keyword.toUpperCase();
  const qLower = keyword.toLowerCase();

  // Normalize accented characters for search
  const normalize = (s: string) =>
    s.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "");
  const qNorm = normalize(keyword);

  // Exact IATA match first
  const exactIata = AIRPORTS_DB.filter(a => a.iata === q);

  // Then prefix matches on IATA
  const prefixIata = AIRPORTS_DB.filter(a =>
    a.iata.startsWith(q) && a.iata !== q
  );

  // Then matches on city/name (normalized)
  const nameMatches = AIRPORTS_DB.filter(a => {
    if (a.iata === q || a.iata.startsWith(q)) return false;
    return (
      normalize(a.city).includes(qNorm) ||
      normalize(a.name).includes(qNorm) ||
      normalize(a.country).includes(qNorm)
    );
  });

  const combined = [...exactIata, ...prefixIata, ...nameMatches];
  // Deduplicate
  const seen = new Set<string>();
  const unique: AirportEntry[] = [];
  for (const a of combined) {
    if (!seen.has(a.iata)) {
      seen.add(a.iata);
      unique.push(a);
    }
    if (unique.length >= limit) break;
  }
  return unique;
}
